#!/bin/sh

# Get the current branch name
branch=$(git rev-parse --abbrev-ref HEAD)

# Check if the branch is 'develop' and prevent commit if it is
if [ "$branch" = "develop" ]; then
    echo "Direct commits to the 'develop' branch are not allowed."
    echo "Please create a new branch and commit there instead."
    exit 1
fi

# Run Lint (fails commit if issues remain)
pnpm lint
if [ $? -ne 0 ]; then
  echo "❌ Linting failed. Fix issues before committing."
  exit 1
fi

# Run lint with auto-fix
# pnpm lint:fix

# Run your build check
# pnpm build
